# Height distance from robot's feet to camera (unit=m)
camera_robot_height: 1.1

# Birds eye view width of the bounding box to modify (unit=m)
box_width: 1.0

# Birds eye view height of the bounding box to modify (unit=m)
box_front: 0.9

# Birds eye view height of the bounding box to modify (unit=m)
box_back: 0.1

# Height (up) of bounding box from Robot's feet (unit=m)
box_up: 0.1

# Depth (down) of bounding box from Robot's feet (unit=m)
box_down: 0.1

# Starting/minimum value of pixels of the depth image sent to the service
image_height_base: 10.0

# Scale that pixel values of the depth images are multiplied by
pixel_height_scale: 1