in_points: "/points2"
in_request: "/map_request"

out_ground: "/ground_pointcloud_new"
out_steps:  "/steps_pointcloud_new"
out_steps_flat: "/steps_flat_new"
out_steps_tranform: "/steps_tranform_new"
out_steps_world_flat: "/steps_world_flat_new"

steps_frame: "/depth_camera_link"
base_link_frame: "/base_link"

# RANSAC
downsample_size: 0.01          # Downsample leaf voxel size. Higher = greater downsampling
ransac_dt: 0.008                # RANSAC distance threshold. Higher = more inclusive

# Octomap
out_steppable: "/steppable_region"
out_obstacle: "/environment"
octomap_frame: "/map"
octomap_resolution: 0.02
out_bounding_box: "/bounding_box_new"
bounding_box: [-2.0, 0, -0.5, 0.5, -0.2, 0.2]  # min_x, max_x, min_y, max_y, min_z, max_z
pre_crop_box: [-0.5, 0.5, -0.45, 2, -2.0, 2.0]  # min_x, max_x, min_y, max_y, min_z, max_z

RUN_MODE: 2 # 1 - 징검다리/외나무다리, 2 - 장애물